service_workshop:
    type: rest
    prefix: /api
    resource: "@CoreAPIBundle/Controller/WorkshopController.php"
    name_prefix:  api_workshop_ # naming collision

service_admin:
    type: rest
    prefix: /api/
    resource: "@CoreAPIBundle/Controller/UserController.php"
    name_prefix:  api_admin_ # naming collision


# Admin API

service_admin_workshop:
    type: rest
    prefix: /api/admin
    resource: "@CoreAPIBundle/Controller/Admin/WorkshopController.php"
    name_prefix:  api_admin_workshop_

service_admin_participants:
    type: rest
    prefix: /api/admin
    resource: "@CoreAPIBundle/Controller/Admin/ParticipantsController.php"
    name_prefix:  api_admin_participants_ # naming collision

service_admin_secure:
    type: rest
    prefix: /api/admin
    resource: "@CoreAPIBundle/Controller/Admin/UserController.php"
    name_prefix:  api_admin_ # naming collision

service_workshop_template:
    type: rest
    prefix: /api/admin/workshops
    resource: "@CoreAPIBundle/Controller/Admin/WorkshopTemplateController.php"
    name_prefix:  api_admin_workshop_template_ # naming collision

service_email:
    type: rest
    prefix: /api/admin
    resource: "@CoreAPIBundle/Controller/Admin/EmailController.php"
    name_prefix:  api_admin_email_ # naming collision

service_email_template:
    type: rest
    prefix: /api/admin/email
    resource: "@CoreAPIBundle/Controller/Admin/EmailTemplateController.php"
    name_prefix:  api_admin_email_template_ # naming collision


