services:
#    core_api.example:
#        class: Core\APIBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     core_api.util.inflector:
         class: Core\APIBundle\Util\Inflector\NoopInflector

     helper:
         class: Core\APIBundle\Service\Helper
         calls:
              - [ setEntityManager, [ '@doctrine.orm.entity_manager' ]]
              - [ setLogger,['@logger']]
              - [ setTwig,['@twig']]
              - [ setContainer,['@service_container']]
              - [ setMailer,['@mailer']]
         tags:
              - { name: monolog.logger, channel: 'participants' }
