api_login_check:
    path: /api/login_check

core_frontend:
    resource: "@CoreFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

restful_services:
    resource: "@CoreAPIBundle/Resources/config/routing.yml"
    type:     rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
