services:
  mail:
    class: Core\CronBundle\Controller\MailController;

#    core_cron.example:
#        class: Core\CronBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
